- name: установка программы X
  hosts: all
  become: yes

  tasks:
   - name: текстовый файл
     copy:
       content: "hello word"
       dest: /tmp/file1
   - name: nginx
     yum:
       name: nginx
       state: latest
       update_cache: yes
   - name: enable
     ansible.builtin.systemd_service:
       name: nginx
       state: started
       enabled: yes
