#ansible-playbook playbook.yml --ask-become-pass 
- name: установка программы X
  hosts: all
  become: yes
  vars:
    ngconf_src: ./nginx.conf
    ngconf_dest: /etc/nginx/nginx.conf 
    html_src: ./index.html
    html_dest: /etc/nginx/index.html

  tasks:
   - name: текстовый файл
     copy:
       content: "hello word"
       dest: /tmp/file1
   - name: nginx установка
     yum:
       name: nginx
       state: latest
       update_cache: yes
   - name: enable
     ansible.builtin.systemd_service:
       name: nginx
       state: started
       enabled: yes
   - name: iptables установка
     yum:
      name: iptables
      state: present
   - name: конфиг
     copy:
       src: "{{ ngconf_src }}"
       dest: "{{ ngconf_dest }}"
   - name: плейсхолдер сайта
     copy:
       src: "{{ html_src }}"
       dest: "{{ html_dest }}"
   - name: iptables правила
     shell: iptables -C INPUT -p tcp --dport 443 -j ACCEPT || iptables -A INPUT -p tcp --dport 443 -j ACCEPT;
            iptables -C INPUT -p tcp --dport 80 -j ACCEPT || iptables -A INPUT -p tcp --dport 80 -j ACCEPT
   - name: огненная стена
     shell: firewall-cmd --permanent --add-port=80/tcp;
            firewall-cmd --permanent --add-port=80/udp;
            firewall-cmd --permanent --add-port=443/tcp;
            firewall-cmd --permanent --add-port=443/udp;
            firewall-cmd --reload
